//
//  OrderDetailsWorker.swift
//  mobile-challenge
//
//  Created by Brendoon Ryos on 01/03/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class OrderDetailsWorker {
  private let networkManager: Networkable
  
  init(networkManager: Networkable = NetworkManager()) {
    self.networkManager = networkManager
  }
  
  func fetchOrderDetails(request: Orders.Details.Request, completion: @escaping ((Result<Order>) -> ())) {
    networkManager.fetchOrderDetails(request: request) { result in
      completion(result)
    }
  }
}
