//
//  LoginRouter.swift
//  mobile-challenge
//
//  Created by Brendoon Ryos on 01/03/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
  func routeToOrders()
}

protocol LoginDataPassing {
  var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
  weak var viewController: LoginViewController?
  var dataStore: LoginDataStore?
  
  // MARK: Routing
  func routeToOrders() {
    let destinationVC = OrdersViewController()
    var destinationDS = destinationVC.router!.dataStore!
    
    passDataToOrders(source: dataStore!, destination: &destinationDS)
    navigateToOrders(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  func navigateToOrders(source: LoginViewController, destination: OrdersViewController) {
    let navigationController = UINavigationController(rootViewController: destination)
    source.present(navigationController, animated: false)
  }
  
  // MARK: Passing data
  func passDataToOrders(source: LoginDataStore, destination: inout OrdersDataStore) {
    destination.loginResponse = source.loginResponse
  }
}
