//
//  LoginWorker.swift
//  mobile-challenge
//
//  Created by Brendoon Ryos on 01/03/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire

class LoginWorker {
  private let networkManager: Networkable
  private let dataStore: LoginStoreProtocol
  
  init(networkManager: Networkable = NetworkManager(), dataStore: LoginStoreProtocol = LoginKeychainStore()) {
    self.networkManager = networkManager
    self.dataStore = dataStore
  }
  
  func signInWithSavedParams(completion: @escaping ((Result<LoginResponse>) -> ())) {
    let params = dataStore.getSignInParams()
    guard let username = params.username, let password = params.password else {
      completion(Result.failure(NSError()))
      return
    }
    let request = Login.SignIn.Request(username: username, password: password)
    signIn(request: request) { result in
      completion(result)
    }
  }
  
  func signIn(request: Login.SignIn.Request, completion: @escaping ((Result<LoginResponse>) -> ())) {
    dataStore.set(username: request.username, password: request.password)
    networkManager.signIn(request: request) { result in
      completion(result)
    }
  }
}
