# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile-challenge' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  plugin 'cocoapods-keys', {
    :project => "mobile-challenge",
    :target => "mobile-challenge",
    :keys => [
    "client_id",
    "client_secret",
    "grant_type",
    "scope"
    ]}

  # Pods for mobile-challenge
  pod 'Reusable'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Moya'
  pod 'KeychainSwift'

  target 'mobile-challengeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

  #target 'mobile-challengeUITests' do
    #inherit! :search_paths
    # Pods for testing
    #pod 'iOSSnapshotTestCase'
  #end

end
