//
//  OrdersModels.swift
//  mobile-challenge
//
//  Created by Brendoon Ryos on 01/03/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Orders {
  // MARK: Use cases
  enum All {
    struct Request {
      let token: String
      let offset: Int
    }
    struct Response {
      let ordersResponse: OrdersResponse?
      let error: Error?
      
      init(ordersResponse: OrdersResponse? = .none, error: Error? = .none) {
        self.ordersResponse = ordersResponse
        self.error = error
      }
    }
    struct ViewModel {
      let ordersResponse: OrdersResponse?
      let error: Error?
      
      var currentCount: Int {
        return ordersResponse?.summary.count ?? 0
      }
      
      init(ordersResponse: OrdersResponse? = .none, error: Error? = .none) {
        self.ordersResponse = ordersResponse
        self.error = error
      }
    }
  }
  
  enum Details {
    struct Request {
      let token: String
      let id: String
    }
    struct Response {
      let order: Order?
      let error: Error?
      
      init(order: Order? =  .none, error: Error? = .none) {
        self.order = order
        self.error = error
      }
    }
    struct ViewModel {
      let order: Order?
      let error: Error?
      
      init(order: Order? =  .none, error: Error? = .none) {
        self.order = order
        self.error = error
      }
    }
  }
}
