//
//  OrdersWorker.swift
//  mobile-challenge
//
//  Created by Brendoon Ryos on 01/03/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class OrdersWorker {
  
  private let networkManager: Networkable
  
  init(networkManager: Networkable = NetworkManager()) {
    self.networkManager = networkManager
  }
  
  func fetchOrders(request: Orders.All.Request, completion: @escaping ((Result<OrdersResponse>) -> ())) {
    networkManager.fetchOrders(request: request) { result in
      completion(result)
    }
  }
}
