//
//  OrdersRouter.swift
//  mobile-challenge
//
//  Created by Brendoon Ryos on 01/03/19.
//  Copyright (c) 2019 Brendoon Ryos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol OrdersRoutingLogic {
  func routeToOrderDetails()
}

protocol OrdersDataPassing {
  var dataStore: OrdersDataStore? { get }
}

class OrdersRouter: NSObject, OrdersRoutingLogic, OrdersDataPassing {
  weak var viewController: OrdersViewController?
  var dataStore: OrdersDataStore?
  
  // MARK: Routing
  
  func routeToOrderDetails() {
    let destinationVC = OrderDetailsViewController()
    var destinationDS = destinationVC.router!.dataStore!
    
    passDataToOrderDetails(source: dataStore!, destination: &destinationDS)
    navigateToOrderDetails(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  func navigateToOrderDetails(source: OrdersViewController, destination: OrderDetailsViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  func passDataToOrderDetails(source: OrdersDataStore, destination: inout OrderDetailsDataStore) {
    destination.orderId = source.orderId
    destination.token = source.loginResponse?.accessToken
  }
}
